version: '3.8'

services:
  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  app:
    build: .
    container_name: node-app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - REDIS_HOST=redis
    depends_on:
      - redis
    restart: always
