jobs:
  test-api:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
      app:
        image: my-app
        ports:
          - 3000:3000
        options: >-
          --env REDIS_HOST=redis

    steps:
      - uses: actions/checkout@v4

      - name: Wait for app to start
        run: |
          echo "Waiting for Node app to start..."
          for i in $(seq 1 10); do
            if curl -s http://app:3000 >/dev/null; then
              echo "Node app is up!"
              break
            fi
            echo "Attempt $i failed. Waiting 5s..."
            sleep 5
          done

      - name: Run API tests
        run: |
          curl -s -X POST http://app:3000/api/x-transaction-redis \
            -H "Content-Type: application/json" \
            -H "x-transaction-id: 2025-08-13" \
            -d '{"message":"Test from CI/CD"}'
