name: Build and Test Redis Image

on: [push]

jobs:
  build_and_test_redis:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Redis Docker image
        id: build
        run: |
          docker build -t my-redis-image .
          echo "Image built successfully!"

      - name: Run Redis container
        id: run
        run: |
          # The -d flag runs the container in detached mode (in the background)
          docker run --name test-redis -d my-redis-image
          echo "Container started."

      - name: Wait for Redis to be ready
        # Give the container a few seconds to start up completely
        run: sleep 5

      - name: Test Redis connection with ping/pong
        id: test
        run: |
          # Use docker exec to run a command inside the running container.
          # We call redis-cli and pipe its output to a variable.
          RESULT=$(docker exec test-redis redis-cli ping)
          
          # Check if the result is 'PONG'
          if [[ "$RESULT" == "PONG" ]]; then
            echo "✅ Redis test successful: Ping responded with Pong!"
          else
            echo "❌ Redis test failed: Expected PONG, got '$RESULT'"
            exit 1
          fi

      - name: Stop and remove container
        # This step cleans up the container whether the test passed or failed
        if: always()
        run: docker rm -f test-redis
