name: curl-to-redis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  post-to-redis:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7-alpine
        options: >-
          --name redis-server
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        # This tells the step to run the command in the root of your repository
        working-directory: ./
        run: npm install

      - name: Run tests with Redis
        working-directory: ./
        env:
          REDIS_HOST: redis
          REDIS_PORT: 6379
        run: npm test # Or whatever command you use to run your tests
